#pragma once

// Only activate the commands that are used. Every command takes 100 bytes, wether used or not.
// extern uint16_t SHARP_POWER_TOGGLE;
// extern uint16_t SHARP_SOURCE;
// extern uint16_t SHARP_HDMI;
extern uint16_t SHARP_NUM_1;
extern uint16_t SHARP_NUM_2;
extern uint16_t SHARP_NUM_3;
extern uint16_t SHARP_NUM_4;
extern uint16_t SHARP_NUM_5;
extern uint16_t SHARP_NUM_6;
extern uint16_t SHARP_NUM_7;
extern uint16_t SHARP_NUM_8;
extern uint16_t SHARP_NUM_9;
extern uint16_t SHARP_NUM_0;
// extern uint16_t SHARP_TTXMIX;
// extern uint16_t SHARP_PRECH;
// extern uint16_t SHARP_VOL_MINUS;
// extern uint16_t SHARP_VOL_PLUS;
// extern uint16_t SHARP_MUTE_TOGGLE;
// extern uint16_t SHARP_CHLIST;
extern uint16_t SHARP_CHANNEL_UP;
extern uint16_t SHARP_CHANNEL_DOWN;
extern uint16_t SHARP_MENU;
// extern uint16_t SHARP_APPS;
extern uint16_t SHARP_GUIDE;
// extern uint16_t SHARP_TOOLS;
// extern uint16_t SHARP_INFO;
extern uint16_t SHARP_UP;
extern uint16_t SHARP_DOWN;
extern uint16_t SHARP_LEFT;
extern uint16_t SHARP_RIGHT;
extern uint16_t SHARP_SELECT;
// extern uint16_t SHARP_RETURN;
extern uint16_t SHARP_EXIT;
// extern uint16_t SHARP_KEY_A;
// extern uint16_t SHARP_KEY_B;
// extern uint16_t SHARP_KEY_C;
// extern uint16_t SHARP_KEY_D;
// extern uint16_t SHARP_FAMILYSTORY;
// extern uint16_t SHARP_SEARCH;
// extern uint16_t SHARP_DUALI_II;
// extern uint16_t SHARP_SUPPORT;
// extern uint16_t SHARP_PSIZE;
// extern uint16_t SHARP_ADSUBT;
extern uint16_t SHARP_REWIND;
extern uint16_t SHARP_PAUSE;
extern uint16_t SHARP_FASTFORWARD;
// extern uint16_t SHARP_RECORD;
extern uint16_t SHARP_PLAY;
// extern uint16_t SHARP_STOP;
extern uint16_t SHARP_POWER_OFF;
extern uint16_t SHARP_POWER_ON;
extern uint16_t SHARP_INPUT_HDMI_1;
extern uint16_t SHARP_INPUT_HDMI_2;
extern uint16_t SHARP_INPUT_HDMI_3;
// extern uint16_t SHARP_INPUT_HDMI_4;
// extern uint16_t SHARP_INPUT_COMPONENT;
extern uint16_t SHARP_INPUT_TV;

void register_device_sharpTV();
