#!/usr/bin/env python3
"""Convert a PNG to an LVGL LV_IMG_CF_ALPHA_8BIT C source file.

The output matches the format used by gui_appleTV_assets.c (hand-checked-in
files generated by the LVGL Online Image Converter): one alpha byte per
pixel, recolored at runtime to the foreground color.

Usage:
  png_to_lvgl_alpha8.py <input.png> <output.c> <symbol_name> [size]

Default size is 16 (px), producing a square 16x16 icon suitable for the
status bar. The output declares both the byte array (<name>_map) and the
lv_img_dsc_t struct (<name>).
"""

import os
import sys
from PIL import Image


def convert(png_path: str, c_path: str, name: str, size: int) -> None:
    img = Image.open(png_path).convert("RGBA")
    img = img.resize((size, size), Image.LANCZOS)
    alpha = img.split()[-1]  # alpha channel
    data = alpha.tobytes()   # row-major, top-to-bottom — what LVGL wants
    assert len(data) == size * size

    rows = []
    bytes_per_row = size  # output one image-row per source-row of the C array
    for y in range(size):
        row_bytes = data[y * bytes_per_row:(y + 1) * bytes_per_row]
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in row_bytes) + ",")

    body = "\n".join(rows)

    out = f"""\
// Auto-generated by tools/png_to_lvgl_alpha8.py from {os.path.basename(png_path)}.
// Do not edit by hand — re-run the script to regenerate.

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {name}_map[] = {{
{body}
}};

const lv_img_dsc_t {name} = {{
  .header.cf = LV_IMG_CF_ALPHA_8BIT,
  .header.always_zero = 0,
  .header.reserved = 0,
  .header.w = {size},
  .header.h = {size},
  .data_size = {size * size},
  .data = {name}_map,
}};
"""
    with open(c_path, "w") as f:
        f.write(out)


if __name__ == "__main__":
    if len(sys.argv) not in (4, 5):
        print(__doc__)
        sys.exit(1)
    size = int(sys.argv[4]) if len(sys.argv) == 5 else 16
    convert(sys.argv[1], sys.argv[2], sys.argv[3], size)
    print(f"wrote {sys.argv[2]} ({size}x{size}, alpha-8bit, {size * size} bytes)")
